### ISSUE TITLE
Parse errors: Bad plan.  You planned 15 tests but ran 13

### ISSUE THREAD

**Issue by pecastro** [dagolden/Test-TempDir-Tiny#12]
David, 

I ended up trying to install the module in a weird setup in which my path had spaces.
This doesn't bode well with https://github.com/dagolden/Test-TempDir-Tiny/blob/master/t/basic.t#L109

Cheers,

    PECastro

**Comment by xdg** [comment]
I've shipped 0.13-TRIAL to CPAN.  Please give it a try and let me know if it fixes the problem.

**Comment by xdg** [comment]
I'm closing this ticket.  Please reopen if the issue continues.
