### ISSUE TITLE
tests currently fail on windows

### ISSUE THREAD

**Issue by wchristian** [dagolden/Test-TempDir-Tiny#3]
See: http://matrix.cpantesters.org/?dist=Test-TempDir-Tiny+0.003

**Comment by wchristian** [comment]
I'm still seeing issues with this: https://gist.github.com/wchristian/40bab92421ee0e57025a

**Comment by dagolden** [comment]
Interesting, I wasn't, but I also bogged down trying to use File::Spec to give windows pathnames and that broke a bunch of tests, too.  I'll dig in more.

**Comment by wchristian** [comment]
I'm sorry that this is causing you to waste time, but i also appreciate you looking into it. :)

**Comment by dagolden** [comment]
Fixed in 0.004 on CPAN
