### ISSUE TITLE
Is there an easy way to retain the directories?

### ISSUE THREAD

**Issue by jscook** [dagolden/Test-TempDir-Tiny#5]
Hello,

Thanks for the great module.

I was wondering if there was an easy way to retain the directories rather than have them go away after test success. I would use something like that when creating new tests and verifying behavior.

Looking through the source briefly makes me think no, but I thought I'd ask.

Thanks,

Justin

**Comment by dagolden** [comment]
Maybe add an environment variable check to the `_cleanup` at the top of the sub:

```
return if $ENV{PERL_TEST_TEMPDIR_TINY_NOCLEANUP};
```
